<?php

namespace app\models;

use yii\db\ActiveRecord;

/**
 * Class District
 * @package app\models
 *
 * @property int $id [int(11)]
 * @property string $name
 */
class District extends ActiveRecord
{
	public static function tableName()
	{
		return '{{%districts}}'; // TODO: Change the autogenerated stub
	}

	public function getStreets()
	{
		return $this->hasMany(Street::className(), ['id' => 'id_street'])
			->viaTable('street_district', ['id_district' => 'id']);
	}
}
